# Generated by Django 3.1.2 on 2020-10-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplecounter',
            name='name',
            field=models.CharField(default='ttoto', max_length=256),
            preserve_default=False,
        ),
    ]
