# Generated by Django 3.1.2 on 2020-10-31 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201031_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplecounter',
            old_name='sensor',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='peoplecounter',
            name='people_id',
            field=models.CharField(default=uuid.UUID('d5852bcb-0a68-4d7d-93e3-52dd79f4a292'), max_length=256, primary_key=True, serialize=False),
        ),
    ]
