# Generated by Django 3.1.2 on 2020-10-31 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201031_1400'),
    ]

    operations = [
        migrations.DeleteModel(name='Sensor', ),
        migrations.AlterField(
            model_name='peoplecounter',
            name='people_id',
            field=models.CharField(
                default=uuid.UUID('eaff7736-8baf-4818-bf52-7aa78f67f8fb'),
                max_length=256,
                primary_key=True,
                serialize=False),
        ),
    ]
