# Generated by Django 3.1.2 on 2020-10-31 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201031_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplecounter',
            old_name='status',
            new_name='status_in',
        ),
        migrations.AddField(
            model_name='peoplecounter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peoplecounter',
            name='people_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='peoplecounter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peoplecounter',
            name='status_out',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='peoplecounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
