# Generated by Django 3.1.2 on 2020-10-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201031_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecounter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
