# Generated by Django 3.1.2 on 2020-10-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201031_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplecounter',
            name='status_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peoplecounter',
            name='status_out',
            field=models.IntegerField(default=0),
        ),
    ]
